### ISSUE TITLE
TabBar icons wrong render

### ISSUE THREAD

**Issue by molayab** [opelty/blacklist-ios#13]
# TabBar icons wrong render
## Description
The icons in the tab bar are showing wrong, the bottom margin is missing. See image attached below.

## Observations
The issue was found on iPhone 8

## Media

![simulator screen shot - iphone 8 - 2018-02-10 at 03 47 52](https://user-images.githubusercontent.com/1709983/36060341-ac34f40e-0e15-11e8-9c0b-eef12f65a695.png)

**Comment by santicarmo31** [comment]
I'm looking at it @molayab

**Comment by molayab** [comment]
This issue was solved. Thank you @santicarmo31
