### ISSUE TITLE
Custom Navigation Bar

### ISSUE THREAD

**Issue by molayab** [opelty/blacklist-ios#7]
# Acceptance Criteria 

We need to add the following Navigation Bar as the default bar. 

 - The bar must be black according to the creative resource attached.
 - The text must be aligned to left with minimum margin form left side that allows put a back arrow (arrow attached)
 - The font of the bar must be the same (Lobster) for the creative resource attached.
 - The bar must have an option to add a right item (image) like the attached resource.
    - Only in the Home view, the right item must be the settings image (attached too).
 - Bar height is 90 points including the status bar and the safe area (iOS)
 - The status bar font color must be white.
 - The status bar background color must be the same of the Navigation Bar.
 - This component must be modular and reusable.

## Creative Resources

<img width="600" alt="screen shot 2018-02-03 at 10 30 15 pm" src="https://user-images.githubusercontent.com/1709983/35774027-db866b40-0931-11e8-87de-3b95f094f51b.png">

### Fonts 

[Fonts.zip](https://github.com/opelty/blacklist-ios/files/1692453/Fonts.zip)

### Icons 

[Icons.zip](https://github.com/opelty/blacklist-ios/files/1692445/Icons.zip)

### Predefined Colors 

 - Background Color: ```0x222831```

**Comment by lopezjosed89** [comment]
@molayab @santicarmo31  guys what do you think if the "Blacklist" label is centered instead of the aligned to the left, I mean now is is very close to the back arrow so I feel like is saying "Back to to the blacklist" or is that the intention here?

**Comment by santicarmo31** [comment]
@lopezjosed89 I agree with you, it should be centered
